version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=notepad
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - laravel

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
    driver: local
